[package]
name = "barakah"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
axum-error = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.25.0", default-features = false, features = ["macros", "rt-multi-thread"] }
